#include "main.h"
#include "spi.h"
#include "delay.h"
#include <stdio.h>

/*
top
SPI_SSP_LOW  // slave select is high active
SPI_CPHA_HALF // spi first clock edge is issued one-half cycle of transfer cycle
SPI_CPOL_HIGH // clock active high
SPI_MSB_FIRST // the MSB is sent first
SPI_ENB	     // spi module enable
SPI_SS_AUTO  // slave select signal generated automatically
SPI_MST_SEL  // spi master mode
SPI_SSO_ENB  // enable driving slave select signal

sd
SPI_SSP_LOW  // slave select is high active
SPI_CPHA_BEG // spi first clock edge is issued at the beginning of transfer cycle
SPI_CPOL_LOW // clock active low
SPI_MSB_FIRST // the MSB is sent first
SPI_ENB	     // spi module enable
SPI_SS_NORM  // slave select signal generated by SPISSR bits
SPI_MST_SEL  // spi master mode
SPI_SSO_ENB  // enable driving slave select signal
*/



//**** SPI1 ****************

// TOP board
void SPI1_Init(u8 type)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	SPI_InitTypeDef SPI_InitStructure;	
	
	if((Modbus.mini_type == MINI_NEW_TINY) || (Modbus.mini_type == MINI_TINY_ARM))
		return;
	
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_SPI1 | RCC_APB2Periph_GPIOA | RCC_APB2Periph_GPIOC | RCC_APB2Periph_GPIOD, ENABLE);	//PORTB?SPI1???? 


	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_5 | GPIO_Pin_6 | GPIO_Pin_7;			//PA5-SCK, PA6-MISO, PA7-MOSI
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF_PP;  							//PA5/6/7?????? 
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init(GPIOA, &GPIO_InitStructure);										//???GPIOA
	GPIO_SetBits(GPIOA, GPIO_Pin_5 | GPIO_Pin_6 | GPIO_Pin_7);

// top board  NNS PC1

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_1;				
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;			//??????
	GPIO_Init(GPIOC, &GPIO_InitStructure);	
	
// ONLY FOR ARM_SMALL NNS PD3, share SPI1 with top board
	if((Modbus.mini_type == MINI_SMALL) || (Modbus.mini_type == MINI_SMALL_ARM))
	{
		GPIO_InitStructure.GPIO_Pin = GPIO_Pin_3;				
		GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
		GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;			//??????
		GPIO_Init(GPIOD, &GPIO_InitStructure);
	}
	

	SPI_InitStructure.SPI_Direction = SPI_Direction_2Lines_FullDuplex;			//??SPI???????????:SPI??????????
	SPI_InitStructure.SPI_Mode = SPI_Mode_Master;								//??SPI????:????SPI
	SPI_InitStructure.SPI_DataSize = SPI_DataSize_8b;							//??SPI?????:SPI????8????

#if ARM_MINI	
	if(type == 0) // top board 
	{
		SPI_InitStructure.SPI_CPOL = SPI_CPOL_Low;									//???????????????
		SPI_InitStructure.SPI_CPHA = SPI_CPHA_1Edge;								//?????????????(?????)?????
		SPI_InitStructure.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_256;		//??????????:????????256
		if((Modbus.mini_type == MINI_SMALL) || (Modbus.mini_type == MINI_SMALL_ARM))
		{
			TOP_CS = 0;
			SD_CS_SMALL = 1;
		}
	}
	else if(type == 1) // sd card
	{
		SPI_InitStructure.SPI_CPOL = SPI_CPOL_High;									//???????????????
		SPI_InitStructure.SPI_CPHA = SPI_CPHA_2Edge;
		SPI_InitStructure.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_16;		//??????????:????????256
		if((Modbus.mini_type == MINI_SMALL) || (Modbus.mini_type == MINI_SMALL_ARM))
		{
			TOP_CS = 1;
			SD_CS_SMALL = 0;
		}
	}
#endif
	
	SPI_InitStructure.SPI_NSS = SPI_NSS_Soft;									//NSS?????(NSS??)????(??SSI?)??:??NSS???SSI???
	SPI_InitStructure.SPI_FirstBit = SPI_FirstBit_MSB;							//???????MSB???LSB???:?????MSB???
	SPI_InitStructure.SPI_CRCPolynomial = 7;									//CRC???????
	SPI_Init(SPI1, &SPI_InitStructure);											//??SPI_InitStruct???????????SPIx???
 
	SPI_Cmd(SPI1, ENABLE); 														//??SPI??
	
	SPI1_ReadWriteByte(0xff);//????
	SPI1_ReadWriteByte(0xff);//????
	SPI1_ReadWriteByte(0xff);//????
	
	if(type == 1) // sd card
	{
		SPI1_SetSpeed(SPI_BaudRatePrescaler_256);
	}
	else
		SPI1_SetSpeed(SPI_BaudRatePrescaler_16);
}

void SPI1_SetSpeed(u8 SPI_BaudRatePrescaler)
{
	assert_param(IS_SPI_BAUDRATE_PRESCALER(SPI_BaudRatePrescaler));		//????
	SPI1->CR1 &= 0XFFC7; 
	SPI1->CR1 |= SPI_BaudRatePrescaler;									//??SPI1??  
	SPI_Cmd(SPI1, ENABLE);												//SPI1????	  
}

//SPI1 ??????
//TxData:??????
//???:??????
u8 SPI1_ReadWriteByte(u8 TxData)
{		
	u16 retry = 0;
	retry = 0;
	while(SPI_I2S_GetFlagStatus(SPI1, SPI_I2S_FLAG_TXE) == RESET)
	{
		retry++;
		if(retry > 0xffff) {return 0;}
	};
	SPI_I2S_SendData(SPI1, TxData);
	retry = 0;
	while(SPI_I2S_GetFlagStatus(SPI1, SPI_I2S_FLAG_RXNE) == RESET)
	{
		retry++;
		if(retry > 0xffff) {return 0;}
	};
	return SPI_I2S_ReceiveData(SPI1);
}
// SD card
void SPI3_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	SPI_InitTypeDef SPI_InitStructure;	
	
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB | RCC_APB2Periph_GPIOC | RCC_APB2Periph_GPIOD, ENABLE);	//PORTB?SPI1???? 
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_SPI3, ENABLE);
	
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_3 | GPIO_Pin_4 | GPIO_Pin_5;			//PA5-SCK, PA6-MISO, PA7-MOSI
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF_PP;  							//PA5/6/7?????? 
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init(GPIOB, &GPIO_InitStructure);										//???GPIOA
	GPIO_SetBits(GPIOB, GPIO_Pin_3 | GPIO_Pin_4 | GPIO_Pin_5);



	// PC5 - ss3
	

	if((Modbus.mini_type == MINI_BIG) || (Modbus.mini_type == MINI_BIG_ARM))
	{
		GPIO_InitStructure.GPIO_Pin = GPIO_Pin_5;				
		GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
		GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;			//??????
		GPIO_Init(GPIOC, &GPIO_InitStructure);
		GPIO_ResetBits(GPIOC, GPIO_Pin_5);
	}
	else if((Modbus.mini_type == MINI_NEW_TINY) || (Modbus.mini_type == MINI_TINY_ARM))
	{
		GPIO_InitStructure.GPIO_Pin = GPIO_Pin_9;				
		GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
		GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;			//??????
		GPIO_Init(GPIOD, &GPIO_InitStructure);
		GPIO_ResetBits(GPIOD, GPIO_Pin_9);
	}
	
	SPI_InitStructure.SPI_Direction = SPI_Direction_2Lines_FullDuplex;			//??SPI???????????:SPI??????????
	SPI_InitStructure.SPI_Mode = SPI_Mode_Master;								//??SPI????:????SPI
	SPI_InitStructure.SPI_DataSize = SPI_DataSize_8b;							//??SPI?????:SPI????8????
 
//// SD card
	SPI_InitStructure.SPI_CPOL = SPI_CPOL_High;									//???????????????
	SPI_InitStructure.SPI_CPHA = SPI_CPHA_2Edge;
	SPI_InitStructure.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_16;		//??????????:????????256
	
	SPI_InitStructure.SPI_NSS = SPI_NSS_Soft;									//NSS?????(NSS??)????(??SSI?)??:??NSS???SSI???
	SPI_InitStructure.SPI_FirstBit = SPI_FirstBit_MSB;							//???????MSB???LSB???:?????MSB???
	SPI_InitStructure.SPI_CRCPolynomial = 7;									//CRC???????
	SPI_Init(SPI3, &SPI_InitStructure);											//??SPI_InitStruct???????????SPIx???
 
	SPI_Cmd(SPI3, ENABLE); 														//??SPI??
	
	SPI3_ReadWriteByte(0xff);//????
	SPI3_SetSpeed(SPI_BaudRatePrescaler_256);
}

//SPI1??????
//SPI_BaudRatePrescaler_2   2??   
//SPI_BaudRatePrescaler_8   8??   
//SPI_BaudRatePrescaler_16  16??  
//SPI_BaudRatePrescaler_256 256?? 
extern u16 Test[50];
void SPI3_SetSpeed(u8 SPI_BaudRatePrescaler)
{
	assert_param(IS_SPI_BAUDRATE_PRESCALER(SPI_BaudRatePrescaler));		//????
	SPI3->CR1 &= 0XFFC7; 
	SPI3->CR1 |= SPI_BaudRatePrescaler;									//??SPI1??  
	SPI_Cmd(SPI3, ENABLE);												//SPI1????	  
}

//SPI1 ??????
//TxData:??????
//???:??????
u8 SPI3_ReadWriteByte(u8 TxData)
{		
	u16 retry = 0;
	while(SPI_I2S_GetFlagStatus(SPI3, SPI_I2S_FLAG_TXE) == RESET)
	{
		retry++;
		if(retry > 0xffff) {return 0;}
	};
	SPI_I2S_SendData(SPI3, TxData);
	retry = 0;
	while(SPI_I2S_GetFlagStatus(SPI3, SPI_I2S_FLAG_RXNE) == RESET)
	{
		retry++;
		if(retry > 0xffff) {return 0;}
	};
	return SPI_I2S_ReceiveData(SPI3);
}

// ETHERNET 
//************ SPI2 ********************
void SPI2_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	SPI_InitTypeDef SPI_InitStructure;

	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB, ENABLE);//PORTB????
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_SPI2,  ENABLE);//SPI2????

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_13 | GPIO_Pin_14 | GPIO_Pin_15;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF_PP;  							
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init(GPIOB, &GPIO_InitStructure);										//???GPIOA
	GPIO_SetBits(GPIOB, GPIO_Pin_13 | GPIO_Pin_14 | GPIO_Pin_15);  				//PA5/6/7??

	SPI_StructInit(&SPI_InitStructure);
	SPI_InitStructure.SPI_Direction = SPI_Direction_2Lines_FullDuplex;			//??SPI???????????:SPI??????????
	SPI_InitStructure.SPI_Mode = SPI_Mode_Master;								//??SPI????:????SPI
	SPI_InitStructure.SPI_DataSize = SPI_DataSize_8b;							//??SPI?????:SPI????8????
//	SPI_InitStructure.SPI_CPOL = SPI_CPOL_High;									//???????????????
//	SPI_InitStructure.SPI_CPHA = SPI_CPHA_2Edge;								//?????????????(?????)?????
 	SPI_InitStructure.SPI_CPOL = SPI_CPOL_Low;									//???????????????
 	SPI_InitStructure.SPI_CPHA = SPI_CPHA_1Edge;								//?????????????(?????)?????
	SPI_InitStructure.SPI_NSS = SPI_NSS_Soft;									//NSS?????(NSS??)????(??SSI?)??:??NSS???SSI???
	SPI_InitStructure.SPI_BaudRatePrescaler = SPI_BaudRatePrescaler_256;		//??????????:????????256
	SPI_InitStructure.SPI_FirstBit = SPI_FirstBit_MSB;							//???????MSB???LSB???:?????MSB???
	SPI_InitStructure.SPI_CRCPolynomial = 7;									//CRC???????
	SPI_Init(SPI2, &SPI_InitStructure);											//??SPI_InitStruct???????????SPIx???
 
	SPI_Cmd(SPI2, ENABLE); 														//??SPI??
	SPI2_ReadWriteByte(0xff);//????
	
	//SPI2_SetSpeed(SPI_BaudRatePrescaler_256);
 	SPI2_SetSpeed(SPI_BaudRatePrescaler_8);	//SCK??=36M/4=9M


}

//SPI1??????
//SPI_BaudRatePrescaler_2   2??   
//SPI_BaudRatePrescaler_8   8??   
//SPI_BaudRatePrescaler_16  16??  
//SPI_BaudRatePrescaler_256 256?? 
void SPI2_SetSpeed(u8 SPI_BaudRatePrescaler)
{
	assert_param(IS_SPI_BAUDRATE_PRESCALER(SPI_BaudRatePrescaler));		//????
	SPI2->CR1 &= 0XFFC7; 
	SPI2->CR1 |= SPI_BaudRatePrescaler;									//??SPI2??  
	SPI_Cmd(SPI2, ENABLE);												//SPI2????	  
}

//SPI1 ??????
//TxData:??????
//???:??????
u8 SPI2_ReadWriteByte(u8 TxData)
{		
	u16 retry = 0;
	while(SPI_I2S_GetFlagStatus(SPI2, SPI_I2S_FLAG_TXE) == RESET)
	{
		retry++;
		if(retry > 0xffff) return 0;
	};
	SPI_I2S_SendData(SPI2, TxData);
	retry = 0;
	while(SPI_I2S_GetFlagStatus(SPI2, SPI_I2S_FLAG_RXNE) == RESET)
	{
		retry++;
		if(retry > 0xffff) return 0;
	};
	return SPI_I2S_ReceiveData(SPI2);
}